# .helm/core/envs/prod/values.yaml
replicaCount: 1

image:
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent

service:
  name: ""
  type: ClusterIP
  port: 80

ingress:
  className: nginx
  enabled: true
  host: ""
  tls:
    secretName: wildcard-tls

container:
  resources:
    requests:
      cpu: 5m
      memory: 64Mi
    limits:
      cpu: 10m
      memory: 128Mi